---
title: "PsA"
author: "Kendall Anderson"
date: "11/8/2018"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(rlist)
```

```{r}
clean_one <- read.csv("PsA_clean.csv", na.strings=c("","NA"," "))
```

```{r}
clean_one$race<-"unknown"
clean_one$hispanic_latino<-"unknown"
```

```{r}
clean_one <- clean_one %>% mutate(hispanic_latino = ifelse(Hispanic_Latino_Yes == 1 , "yes", hispanic_latino))
clean_one <- clean_one %>% mutate(hispanic_latino = ifelse(Hispanic_Latino_No == 1 , "no", hispanic_latino))
clean_one <- clean_one %>% mutate(hispanic_latino = ifelse(Hispanic_Latino_Not_Reported == 1 , "unknown", hispanic_latino))
clean_one <- clean_one %>% mutate(hispanic_latino = ifelse(Hispanic_Latino_Unknown == 1 , "unknown", hispanic_latino))
```

```{r}
clean_one <- clean_one %>% mutate(race = ifelse(WHITE == 1 , "white", race))
clean_one <- clean_one %>% mutate(race = ifelse(BLACK == 1 , "black", race))
clean_one <- clean_one %>% mutate(race = ifelse(NATIVE_AMERICAN == 1 , "native_american", race))
clean_one <- clean_one %>% mutate(race = ifelse(NATIVE_HAWAIIAN_PACIFIC_ISLANDER == 1 , "native_hawaiian_pacific_islander", race))
clean_one <- clean_one %>% mutate(race = ifelse(OTHER == 1 , "other", race))
clean_one <- clean_one %>% mutate(race = ifelse(NOT_REPORTED == 1 , "unknown", race))
clean_one <- clean_one %>% mutate(race = ifelse(UNKNOWN == 1 , "unknown", race))
```

```{r}
ggplot(clean_one, aes(race, fill=hispanic_latino)) +
  geom_bar()+
  geom_text(stat='count', aes(label=..count..), vjust=-0.2)
```

```{r}
clean_one$Dactylitis <- as.character(clean_one$Dactylitis)
clean_one$Dactylitis[is.na(clean_one$Dactylitis)] <- "Unknown"
clean_one <- clean_one %>% mutate(Dactylitis = ifelse(Dactylitis == "Unavailable" , "Unknown", Dactylitis))
```

```{r}
ggplot(clean_one, aes(x=Arthritis_Score, y=Joint_Count, colour=Dactylitis))+
         geom_point()
```

```{r}
# create drug column
clean_one$drug_type<- "none"
clean_one$biologic_manual <- "none"
clean_one$non_biologic_manual <- "none"
```

```{r}
# assign Yes to biologic manual column if patient is taking a biologic drug
clean_one <- clean_one %>% mutate(biologic_manual = ifelse(Cosentyx_Secukinumab == "Yes" | Adalimumab_Humira == "Yes" | Certolizumab_Pegol_Cimzia == "Yes" | Etanercept_Enbrel == "Yes" | Golimumab_Simponi == "Yes" | Infliximab_Remicade == "Yes" | Ustekinumab_Stelara == "Yes" | Biologic == "Yes", "Yes", biologic_manual))

# assign Yes to non-biologic manual column if patient is taking a non-biologic drug
clean_one <- clean_one %>% mutate(non_biologic_manual = ifelse(Sulfasalazine == "Yes" | Apremilast == "Yes" | Azathioprine_Imuran == "Yes" | Hydroxychloroquine_Plaquenil == "Yes" | Leflunomide_Arava == "Yes" | Methotrexate_Rheumatrex == "Yes" | Mycophenolate_mofetil_CellCept == "Yes", "Yes", non_biologic_manual))
```

```{r}
# both
clean_one <- clean_one %>% mutate(drug_type = ifelse(biologic_manual == "Yes" & non_biologic_manual == "Yes", "both", drug_type))

# biologic
clean_one <- clean_one %>% mutate(drug_type = ifelse(biologic_manual == "Yes" & (non_biologic_manual == "No" | non_biologic_manual == "none" | is.na(non_biologic_manual)), "biologic", drug_type))

# non-biologic
clean_one <- clean_one %>% mutate(drug_type = ifelse((biologic_manual == "No" |  biologic_manual == "none" | is.na(biologic_manual)) & (non_biologic_manual == "Yes"), "non-biologic", drug_type))

# none
clean_one <- clean_one %>% mutate(drug_type = ifelse((biologic_manual == "No" |  biologic_manual == "none" | is.na(biologic_manual)) & (non_biologic_manual == "No" | non_biologic_manual == "none" | is.na(non_biologic_manual)), "neither", drug_type))
```

```{r}
# make sure there are no NAs for drug type
sum(is.na(clean_one$drug_type) == TRUE)
```

```{r}
# plot distribution of drug types or combinations in PSA dataset
ggplot(clean_one, aes(drug_type))+
  geom_bar(fill="tomato3")+
  geom_text(stat='count', aes(label=..count..), vjust = -0.5)
```

```{r}
clean_one$PAC_ID <- as.character(clean_one$PAC_ID)
clean_one$Date <- as.character(clean_one$Date)
```

```{r}
# convert patient visit dates into date variables
clean_one$Date <- as_date(clean_one$Date)
```

```{r}
ggplot(clean_one[1:100,], aes(x=Date, y=PAC_ID, color=drug_type))+
  geom_point()
```

```{r}
head(clean_one)
str(clean_one)
```

```{r}
names(clean_one)
class(clean_one)
```

```{r}
#subset by Event_Name
EN <- split(clean_one, clean_one$Event_Name)
```

```{r}
#assign dataframe for each visit
lapply(seq_along(EN), function(x) {
    assign(c("B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P")[x], EN[[x]], envir=.GlobalEnv)
    }
)
```

```{r}
as.tibble(Fac_only_B)
```

```{r}
#feature selection B -- for joint count
library(leaps)
B$Joint_Count <- as.factor(B$Joint_Count)
FAC<- sapply(B, function(x) is.factor(x))
Fac_only_B <- B[, FAC]
Fac_only_B_1 <- which(sapply(Fac_only_B, function(x) length(unique(x))<2)) # see which factor has only one level
Fac_only_B_EN <- Fac_only_B[,4:67]

str(Fac_only_B_EN)
Fac_only_B_EN_non1 <-Fac_only_B_EN[, sapply(Fac_only_B_EN, nlevels) > 1]
str(Fac_only_B_EN_non1)
#fit <- regsubsets(Joint_Count_F ~., Fac_only_B_EN_non1,  nvmax=19,	method="forward")
library(glmnet)
summary(Fac_only_B_EN_non1$Joint_Count)
glmmod <- glmnet(B, y=as.factor(B$Joint_Count), alpha=1, family="binomial")

```

```{r}
PAC_ID_meds <- read.csv("PAC_ID_meds.csv")
```

```{r}
# find all antibiotics entries in the meds dataframe
antibiotics <- list(grep("Penicillin|Amoxicillin|Tigecycline|Doxycycline|Ceftazidime|Cefpodoxime|Cefazolin|CeftazIDIME|CefazoLIN|CefTRIAXone|Ceftriaxone|CeftriaXONE|CefePIME|Ciprofloxacin|Levofloxacin|Clindamycin|Azithromycin|Erythromycin|Sulfamethoxazole|Vancomycin|Gentamicin|Amikacin|Meropenem|Neomycin|Isoniazid|Piperacillin|Tazobactam|Linezolid|Mupirocin|Tobramycin|Clarithromycin|Daptomycin|Ampicillin|Dicloxacillin|Oxacillin|Nafcillin|Minocycline", PAC_ID_meds$Name, ignore.case = TRUE))
```

```{r}
antibiotics_df <- as.data.frame(antibiotics)
```

```{r}
View(antibiotics_df)
```

```{r}
# duplicate column with PAC_IDs that took antibiotics, call column X so it can bind to meds df
antibiotics_df$X <- antibiotics_df$c.450L..527L..529L..540L..543L..578L..606L..612L..617L..619L..
```

```{r}
# remove old column with long obnoxious name
antibiotics_df <- subset(antibiotics_df, select = -c(c.450L..527L..529L..540L..543L..578L..606L..612L..617L..619L..))
```

```{r}
# merge patient IDs of people who took antibiotics with the meds they took and when
antibiotics_only <- merge(antibiotics_df, PAC_ID_meds)
```

```{r}
View(antibiotics_only)
```

```{r}
# convert release date into charcter so it can then be turned into a date
antibiotics_only$ReleaseDate <- as.character(antibiotics_only$ReleaseDate)
```

```{r}
# convert release date into date so it can be ordered by time
antibiotics_only$ReleaseDate <- as_date(antibiotics_only$ReleaseDate)
```

```{r}
# order by date
antibiotics_only <- antibiotics_only[order(as.Date(antibiotics_only$ReleaseDate)),]
```

```{r}
# remove dates that were before the time point of the PSA dataset collection
antibiotics_only <- antibiotics_only %>% filter(ReleaseDate >= as.Date("2014-07-27") & ReleaseDate <= as.Date("2018-03-17"))
```

```{r}
#date_df <- data.frame(B$Date, B$PAC_ID)
#newdata <- date_df[order(date_df$B.Date),]
```